spring:
  h2:
    console:
      enabled: true

  graphql:
    graphiql:
      enabled: true
      printer:
        enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9092/~/test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

